# Vars set in Google console in Cloud Build Triggers
# {} for vars defined in Cloud Build trigger
# https://cloud.google.com/build/docs/deploying-builds/deploy-functions#yaml

steps:
# Deploy Cloud Functions
  - name: 'google/cloud-sdk:slim'
    id: 'Deploy Cloud Function hourly bot'
    dir: '.'
    args: [
          'gcloud', 'functions', 'deploy', 'cercedilla-weather-bot', 
          '--region', 'europe-west1',
          '--runtime', 'python37',
          '--entry-point', 'parrao_weather_bot',
          '--memory', '128MB',
          '--timeout', '120s',
          # '--env-vars-file', './credentials.yaml', # This file doesn't upload to GitHub
          '--service-account', 'cercedilla-weather-bot@appspot.gserviceaccount.com',
          '--trigger-http',
          '--source', '.'
          ]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Cloud Function daily bot'
    args:
    # - gcloud
    - functions
    - deploy
    - cercedilla-weather-daily-bot
    - --region=europe-west1
    - --runtime=python37
    - --entry-point=parrao_weather_bot_daily
    - --memory=128MB
    - --timeout=120s
    # - --env-vars-file=./credentials.yaml # This file doesn't upload to GitHub
    - --service-account='cercedilla-weather-bot@appspot.gserviceaccount.com'
    - --trigger-http
    - --source=.
    # env:
    # Set var with the value of Cloud Build TRIGGER var
    # - '_SERVICE_ACCOUNT=${_SERVICE_ACCOUNT}' 

# Deploy cloud Functions with sh
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   id: 'Cloud Functions deployment'
#   entrypoint: 'bash'
#   args: ['-c', './deploy.sh']
#   env: 
#   # Set vars with the values of Cloud Build TRIGGER triggerCloudFunctions (Substitution variables)
#   - '_SERVICE_ACCOUNT=${_SERVICE_ACCOUNT}' 
